### ISSUE TITLE
JSON with comments

### ISSUE THREAD

**Issue by visr** [openearth/hydro-model-builder#4]
Biggest downside of using JSON for the human made configuration files is that it doesn't support comments.

Perhaps it is a good idea to pull them through a minify as soon as we read them in, which strips out the comments. If we always do that we can still use comments.

```json5
{
  // Desired model cell size in decimal degrees
  "cellsize": 0.01
}
```

**Comment by gena** [comment]
https://en.wikipedia.org/wiki/YAML?
